FROM node:20

WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install ALL dependencies, including devDependencies
RUN npm ci --include=dev

# Copy the rest of your code
COPY . .

ENV CHOKIDAR_USEPOLLING=true

# Command to run the app
CMD ["npm", "run", "server"]